#############################################################################
# Makefile for building: CS1D_Project_2.app/Contents/MacOS/CS1D_Project_2
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  CS1D_Project_2/CS1D_Project_2.pro
# Template: app
# Command: /Users/alvarohernandez/Qt/5.14.1/clang_64/bin/qmake -o Makefile CS1D_Project_2/CS1D_Project_2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -ICS1D_Project_2 -I. -I../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers -I../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.14.1/clang_64/mkspecs/macx-clang -F/Users/alvarohernandez/Qt/5.14.1/clang_64/lib
QMAKE         = /Users/alvarohernandez/Qt/5.14.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/alvarohernandez/Qt/5.14.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/alvarohernandez/Qt/5.14.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CS1D_Project_21.0.0
DISTDIR = /Users/alvarohernandez/Desktop/CS1D\ project\ 2/Take-Me-Out-To-The-Ballgame-master/.tmp/CS1D_Project_21.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/alvarohernandez/Qt/5.14.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/alvarohernandez/Qt/5.14.1/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtSql -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CS1D_Project_2/controller.cpp \
		CS1D_Project_2/graph.cpp \
		CS1D_Project_2/login.cpp \
		CS1D_Project_2/main.cpp \
		CS1D_Project_2/mainwindow.cpp moc_controller.cpp \
		moc_login.cpp \
		moc_mainwindow.cpp
OBJECTS       = controller.o \
		graph.o \
		login.o \
		main.o \
		mainwindow.o \
		moc_controller.o \
		moc_login.o \
		moc_mainwindow.o
DIST          = ../../Qt/5.14.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.14.1/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.14.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.14.1/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.14.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.14.1/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.14.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.14.1/clang_64/mkspecs/features/spec_post.prf \
		CS1D_Project_2/.qmake.stash \
		../../Qt/5.14.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/resources_functions.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.14.1/clang_64/mkspecs/features/lex.prf \
		CS1D_Project_2/CS1D_Project_2/CS1D_Project_2.pro CS1D_Project_2/controller.h \
		CS1D_Project_2/graph.h \
		CS1D_Project_2/login.h \
		CS1D_Project_2/mainwindow.h CS1D_Project_2/controller.cpp \
		CS1D_Project_2/graph.cpp \
		CS1D_Project_2/login.cpp \
		CS1D_Project_2/main.cpp \
		CS1D_Project_2/mainwindow.cpp
QMAKE_TARGET  = CS1D_Project_2
DESTDIR       = 
TARGET        = CS1D_Project_2.app/Contents/MacOS/CS1D_Project_2

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/CS1D_Project_2/CS1D_Project_2.pro


include /Users/alvarohernandez/Qt/5.14.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

CS1D_Project_2.app/Contents/MacOS/CS1D_Project_2: ui_mainwindow.h $(OBJECTS)  
	@test -d CS1D_Project_2.app/Contents/MacOS/ || mkdir -p CS1D_Project_2.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CS1D_Project_2/CS1D_Project_2.pro ../../../Qt/5.14.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.14.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.14.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/resources_functions.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.14.1/clang_64/mkspecs/features/lex.prf \
		CS1D_Project_2/CS1D_Project_2.pro \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Resources/QtSql.prl \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile CS1D_Project_2/CS1D_Project_2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt/5.14.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.14.1/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.14.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.14.1/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.14.1/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.14.1/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.14.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.14.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.14.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/resources_functions.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.14.1/clang_64/mkspecs/features/lex.prf:
CS1D_Project_2/CS1D_Project_2.pro:
../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Resources/QtSql.prl:
../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CS1D_Project_2/CS1D_Project_2.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

CS1D_Project_2.app/Contents/PkgInfo: 
	@test -d CS1D_Project_2.app/Contents || mkdir -p CS1D_Project_2.app/Contents
	@$(DEL_FILE) CS1D_Project_2.app/Contents/PkgInfo
	@echo "APPL????" > CS1D_Project_2.app/Contents/PkgInfo
CS1D_Project_2.app/Contents/Resources/empty.lproj: 
	@test -d CS1D_Project_2.app/Contents/Resources || mkdir -p CS1D_Project_2.app/Contents/Resources
	@touch CS1D_Project_2.app/Contents/Resources/empty.lproj
	
CS1D_Project_2.app/Contents/Info.plist: 
	@test -d CS1D_Project_2.app/Contents || mkdir -p CS1D_Project_2.app/Contents
	@$(DEL_FILE) CS1D_Project_2.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,cpp.CS1D-Project-2,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},cpp.CS1D-Project-2,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,CS1D_Project_2,g" -e "s,@LIBRARY@,CS1D_Project_2,g" -e "s,\$${EXECUTABLE_NAME},CS1D_Project_2,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt/5.14.1/clang_64/mkspecs/macx-clang/Info.plist.app >CS1D_Project_2.app/Contents/Info.plist

all: Makefile \
		CS1D_Project_2.app/Contents/PkgInfo \
		CS1D_Project_2.app/Contents/Resources/empty.lproj \
		CS1D_Project_2.app/Contents/Info.plist CS1D_Project_2.app/Contents/MacOS/CS1D_Project_2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.14.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CS1D_Project_2/controller.h CS1D_Project_2/graph.h CS1D_Project_2/login.h CS1D_Project_2/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents CS1D_Project_2/controller.cpp CS1D_Project_2/graph.cpp CS1D_Project_2/login.cpp CS1D_Project_2/main.cpp CS1D_Project_2/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CS1D_Project_2/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CS1D_Project_2.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.14.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../../../Qt/5.14.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_controller.cpp moc_login.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_controller.cpp moc_login.cpp moc_mainwindow.cpp
moc_controller.cpp: CS1D_Project_2/controller.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDriver \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlError \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QItemDelegate \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QSize \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		moc_predefs.h \
		../../../Qt/5.14.1/clang_64/bin/moc
	/Users/alvarohernandez/Qt/5.14.1/clang_64/bin/moc $(DEFINES) --include '/Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/moc_predefs.h' -I/Users/alvarohernandez/Qt/5.14.1/clang_64/mkspecs/macx-clang -I'/Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/CS1D_Project_2' -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtSql.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/alvarohernandez/Qt/5.14.1/clang_64/lib CS1D_Project_2/controller.h -o moc_controller.cpp

moc_login.cpp: CS1D_Project_2/login.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QCryptographicHash \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qcryptographichash.h \
		moc_predefs.h \
		../../../Qt/5.14.1/clang_64/bin/moc
	/Users/alvarohernandez/Qt/5.14.1/clang_64/bin/moc $(DEFINES) --include '/Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/moc_predefs.h' -I/Users/alvarohernandez/Qt/5.14.1/clang_64/mkspecs/macx-clang -I'/Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/CS1D_Project_2' -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtSql.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/alvarohernandez/Qt/5.14.1/clang_64/lib CS1D_Project_2/login.h -o moc_login.cpp

moc_mainwindow.cpp: CS1D_Project_2/mainwindow.h \
		CS1D_Project_2/controller.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDriver \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlError \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QItemDelegate \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QSize \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		moc_predefs.h \
		../../../Qt/5.14.1/clang_64/bin/moc
	/Users/alvarohernandez/Qt/5.14.1/clang_64/bin/moc $(DEFINES) --include '/Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/moc_predefs.h' -I/Users/alvarohernandez/Qt/5.14.1/clang_64/mkspecs/macx-clang -I'/Users/alvarohernandez/Desktop/CS1D project 2/Take-Me-Out-To-The-Ballgame-master/CS1D_Project_2' -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtSql.framework/Headers -I/Users/alvarohernandez/Qt/5.14.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Users/alvarohernandez/Qt/5.14.1/clang_64/lib CS1D_Project_2/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: CS1D_Project_2/mainwindow.ui \
		../../../Qt/5.14.1/clang_64/bin/uic
	/Users/alvarohernandez/Qt/5.14.1/clang_64/bin/uic CS1D_Project_2/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

controller.o: CS1D_Project_2/controller.cpp CS1D_Project_2/controller.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDriver \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlError \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QItemDelegate \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QSize \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o CS1D_Project_2/controller.cpp

graph.o: CS1D_Project_2/graph.cpp CS1D_Project_2/graph.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o CS1D_Project_2/graph.cpp

login.o: CS1D_Project_2/login.cpp CS1D_Project_2/login.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QCryptographicHash \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qcryptographichash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o CS1D_Project_2/login.cpp

main.o: CS1D_Project_2/main.cpp CS1D_Project_2/mainwindow.h \
		CS1D_Project_2/controller.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDriver \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlError \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QItemDelegate \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QSize \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o CS1D_Project_2/main.cpp

mainwindow.o: CS1D_Project_2/mainwindow.cpp CS1D_Project_2/mainwindow.h \
		CS1D_Project_2/controller.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDatabase \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlDriver \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../../Qt/5.14.1/clang_64/lib/QtSql.framework/Headers/QSqlError \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QItemDelegate \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/QSize \
		../../../Qt/5.14.1/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../../../Qt/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o CS1D_Project_2/mainwindow.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/CS1D_Project_2/bin || mkdir -p $(INSTALL_ROOT)/opt/CS1D_Project_2/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CS1D_Project_2/bin/CS1D_Project_2.app
	
	$(QINSTALL) CS1D_Project_2.app $(INSTALL_ROOT)/opt/CS1D_Project_2/bin/CS1D_Project_2.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CS1D_Project_2/bin/CS1D_Project_2.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/CS1D_Project_2/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

